// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5vsdy-ziZS3oeVIrKYrsStk9ks5X4mk',
    appId: '1:832298348704:web:45504b6b72a244fa7d19c5',
    messagingSenderId: '832298348704',
    projectId: 'study-app-3c413',
    authDomain: 'study-app-3c413.firebaseapp.com',
    storageBucket: 'study-app-3c413.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoklfrTTau0RTqn1azekYEJxOq4hHjDPI',
    appId: '1:832298348704:android:dfcbdfb1672d1b0d7d19c5',
    messagingSenderId: '832298348704',
    projectId: 'study-app-3c413',
    storageBucket: 'study-app-3c413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzX9CllQuR2KVa8AU5EcVtbN2Xy7dRboo',
    appId: '1:832298348704:ios:1f653ef960ccf4787d19c5',
    messagingSenderId: '832298348704',
    projectId: 'study-app-3c413',
    storageBucket: 'study-app-3c413.appspot.com',
    iosClientId: '832298348704-qpjdpja7gplks0ni5cj2strl2hka0d67.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzX9CllQuR2KVa8AU5EcVtbN2Xy7dRboo',
    appId: '1:832298348704:ios:1f653ef960ccf4787d19c5',
    messagingSenderId: '832298348704',
    projectId: 'study-app-3c413',
    storageBucket: 'study-app-3c413.appspot.com',
    iosClientId: '832298348704-qpjdpja7gplks0ni5cj2strl2hka0d67.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
